# Generated by Django 5.0.1 on 2024-01-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
