# Generated by Django 5.0.1 on 2024-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_app', '0002_event_balance_event_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.TextField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('finalize', 'Finalize'), ('fail', 'Failed')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.TextField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')]),
        ),
    ]
